config/routes.rb
Rails.application.routes.draw do
  get 'vue/index'
  resources :mutters do
    get 'api1', on: :collection
  end
  mount ActionCable.server => '/cable'
  
  resources :helloworlds
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # for VueRouter
  get 'helloworlds_vue/',      to: 'vue#index'
  get 'helloworlds_vue/*path', to: 'vue#index'
  get 'mutters_vue/',          to: 'vue#index'
  get 'mutters_vue/*path',     to: 'vue#index'
  get 'app_vue/',     to: 'vue#index'
  get 'app_vue/*path',     to: 'vue#index'
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/helloworld.rb
class Helloworld < ApplicationRecord
end

app/models/mutter.rb
class Mutter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/helloworlds_controller.rb
class HelloworldsController < ApplicationController
  before_action :set_helloworld, only: %i[ show edit update destroy ]

  # GET /helloworlds or /helloworlds.json
  def index
    @helloworlds = Helloworld.all
  end

  # GET /helloworlds/1 or /helloworlds/1.json
  def show
  end

  # GET /helloworlds/new
  def new
    @helloworld = Helloworld.new
  end

  # GET /helloworlds/1/edit
  def edit
  end

  # POST /helloworlds or /helloworlds.json
  def create
    @helloworld = Helloworld.new(helloworld_params)

    respond_to do |format|
      if @helloworld.save
        format.html { redirect_to @helloworld, notice: "Helloworld was successfully created." }
        format.json { render :show, status: :created, location: @helloworld }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @helloworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helloworlds/1 or /helloworlds/1.json
  def update
    respond_to do |format|
      if @helloworld.update(helloworld_params)
        format.html { redirect_to @helloworld, notice: "Helloworld was successfully updated." }
        format.json { render :show, status: :ok, location: @helloworld }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @helloworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helloworlds/1 or /helloworlds/1.json
  def destroy
    @helloworld.destroy
    respond_to do |format|
      format.html { redirect_to helloworlds_url, notice: "Helloworld was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helloworld
      @helloworld = Helloworld.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def helloworld_params
      params.require(:helloworld).permit(:content, :name)
    end
end

app/controllers/mutters_controller.rb
class MuttersController < ApplicationController
  before_action :set_mutter, only: %i[ show edit update destroy ]

  # GET /mutters or /mutters.json
  def index
    @mutters = Mutter.all.order(id: "DESC")
  end

  def api1
    lists = Mutter.all.order(id: "DESC")
    render json: {data: lists}
  end


  # GET /mutters/1 or /mutters/1.json
  def show
  end

  # GET /mutters/new
  def new
    @mutter = Mutter.new
  end

  # GET /mutters/1/edit
  def edit
  end

  # POST /mutters or /mutters.json
  def create
    @mutter = Mutter.new(mutter_params)
    
    respond_to do |format|
      if @mutter.save
        @mutters = Mutter.all.order(id: "DESC")
        format.html { redirect_to @mutter, notice: "Mutter was successfully created." }
        format.json { render json: @mutters }
        ActionCable.server.broadcast 'mutter_channel', message: 'add'
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutters/1 or /mutters/1.json
  def update
    respond_to do |format|
      if @mutter.update(mutter_params)
        format.html { redirect_to @mutter, notice: "Mutter was successfully updated." }
        format.json { render :show, status: :ok, location: @mutter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutters/1 or /mutters/1.json
  def destroy
    @mutter.destroy
    @mutters = Mutter.all.order(id: "DESC")
    respond_to do |format|
      format.html { redirect_to mutters_url, notice: "Mutter was successfully destroyed." }
      format.json { render json: @mutters }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutter
      @mutter = Mutter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mutter_params
      params.require(:mutter).permit(:message, :name)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      
      log_in user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/vue_controller.rb
class VueController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helloworlds_helper.rb
module HelloworldsHelper
end

app/helpers/mutters_helper.rb
module MuttersHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

   # 現在ログイン中のユーザーを返す (いる場合)
   def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end

   # ユーザーがログインしていればtrue、その他ならfalseを返す
   def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/vue_helper.rb
module VueHelper
end

app/views/helloworlds/_form.html.erb
<%= form_with(model: helloworld) do |form| %>
  <% if helloworld.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(helloworld.errors.count, "error") %> prohibited this helloworld from being saved:</h2>

      <ul>
        <% helloworld.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/helloworlds/edit.html.erb
<h1>Editing Helloworld</h1>

<%= render 'form', helloworld: @helloworld %>

<%= link_to 'Show', @helloworld %> |
<%= link_to 'Back', helloworlds_path %>

app/views/helloworlds/index.html.erb
<%= stylesheet_pack_tag 'hello_vue' %>
<%= javascript_pack_tag 'hello_vue' %>

app/views/helloworlds/new.html.erb
<h1>New Helloworld</h1>

<%= render 'form', helloworld: @helloworld %>

<%= link_to 'Back', helloworlds_path %>

app/views/helloworlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @helloworld.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @helloworld.name %>
</p>

<%= link_to 'Edit', edit_helloworld_path(@helloworld) %> |
<%= link_to 'Back', helloworlds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mutters/_form.html.erb
<%= form_with(model: mutter) do |form| %>
  <% if mutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mutter.errors.count, "error") %> prohibited this mutter from being saved:</h2>

      <ul>
        <% mutter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mutters/edit.html.erb
<h1>Editing Mutter</h1>

<%= render 'form', mutter: @mutter %>

<%= link_to 'Show', @mutter %> |
<%= link_to 'Back', mutters_path %>

app/views/mutters/index.html.erb
<%= stylesheet_pack_tag 'mutters_vue' %>
<%= javascript_pack_tag 'mutters_vue' %>

app/views/mutters/new.html.erb
<h1>New Mutter</h1>

<%= render 'form', mutter: @mutter %>

<%= link_to 'Back', mutters_path %>

app/views/mutters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @mutter.message %>
</p>

<p>
  <strong>Name:</strong>
  <%= @mutter.name %>
</p>

<%= link_to 'Edit', edit_mutter_path(@mutter) %> |
<%= link_to 'Back', mutters_path %>

app/views/user_sessions/new.html.erb
<%= stylesheet_pack_tag 'login_vue' %>
<%= javascript_pack_tag 'login_vue' %>

app/views/vue/index.html.erb
<div id="contents"></div>
<%= stylesheet_pack_tag 'index' %>
<%= javascript_pack_tag 'index' %>
<br>
<a href='/helloworlds' data-turbolinks="false">Helloworlds</a><br>
<a href='/mutters' data-turbolinks="false">Mutters</a><br>